---
title: "R Notebook"
output: html_notebook
---

```{r}
library("quantmod")
getSymbols('ONGC.NS',from='1970-01-01',to='2017-05-18')
NIFTY500<-ONGC.NS

```
renaming of the column names 

```{r}
colnames(NIFTY500) <- c("Open", "High", "Low", "Close","Volume","Adjusted")

NIFTY500[,2] <- NIFTY500[,2] +1e-6
NIFTY500[,5] <- NIFTY500[,5] +1e-6

NIFTY500<-as.xts(na.omit(as.data.frame(NIFTY500)))

tail(NIFTY500)
```
#Transform

```{r}
indicator <- function(histdata,margin=0.025,days=10) {
  
  v <- apply(HLC(histdata),1,mean)
  
  r <- matrix(NA,ncol=days,nrow=NROW(histdata))
  for(x in 1:days) r[,x] <- Next(Delt(Cl(histdata),v,k=x),x)
  
  x <- apply(r,1,function(x) sum(x[x > margin | x < -margin]))
  if (is.xts(histdata)) xts(x,time(histdata)) else x
}
```

```{r}
avgrng <- function(x) ATR(HLC(x))[,'atr']
stochas <- function(x) SMI(HLC(x))[,'SMI']
dirind <- function(x) ADX(HLC(x))[,'ADX']
aroonind <- function(x) aroon(x[,c('High','Low')])$oscillator
bands <- function(x) BBands(HLC(x))[,'pctB']
chaikin <- function(x) Delt(chaikinVolatility(x[,c("High","Low")]))[,1]
expavg <- function(x) EMA(CLV(HLC(x)))[,1]
ease <- function(x) EMV(x[,c('High','Low')],x[,'Volume'])[,2]
movavg <- function(x) MACD(Cl(x))[,2]
mnyind <- function(x) MFI(x[,c("High","Low","Close")], x[,"Volume"])
stprev <- function(x) SAR(x[,c('High','Close')]) [,1]
volatile <- function(x) volatility(OHLC(x),calc="garman")[,1]
chande <- function(x) CMO(Cl(x)) [,1]
expdel <- function(x) EMA(Delt(Cl(x))) [,1]
del <- function(x) Delt(Cl(x),k=1:10) [,9:10]
relind <- function(x) RSI(Cl(x)) [,'EMA']
mvmean <- function(x) runMean(Cl(x)) [,1]
mvsd <- function(x) runSD(Cl(x)) [,1]



```
#Explore
```{r}
candle <- candleChart(last(NIFTY500,'3 months'),theme='white',TA=NULL)
addindicator <- newTA(FUN=indicator,col='blue',legend="TargetReturn")
addindicator()
```
```{r}
chartSeries(NIFTY500, subset='last 3 months')
addBBands(n = 20, sd = 2, ma = "SMA", draw = 'bands', on = -1)
```
```{r}

data.model <- specifyModel(indicator(NIFTY500) ~ del(NIFTY500) + avgrng(NIFTY500) + dirind(NIFTY500)
                           + aroonind(NIFTY500) + bands(NIFTY500)  + chaikin(NIFTY500) 
                  + expavg(NIFTY500)+ chande(NIFTY500) + expdel(NIFTY500) + volatile(NIFTY500)
                                             + movavg(NIFTY500) + mnyind(NIFTY500)  
                  + relind(NIFTY500) + stprev(NIFTY500) + mvmean(NIFTY500) + mvsd(NIFTY500) 
                  + ease(NIFTY500) + stochas(NIFTY500),na.rm=TRUE)

set.seed(1234)


```
